import type { Worldline } from './types';

export const defaultWorldline: Worldline = {
  id: 'default-worldline',
  title: '1999年、夏の終わり',
  era: '1999年',
  place: '地方の海辺の町',
  role: '高校2年生',
  mood: '切なくて懐かしい',
  summary: '存在しないはずなのに、どこか自分の記憶のように感じる夏の自分史。',
  album: [
    '放課後の教室。窓の外だけがやけに明るかった。',
    '夏祭りの帰り道。話したいことを半分だけ残した。',
    '駅前のコンビニ。アイスの袋が少し溶けていた。',
  ],
  line: [
    '相手: ねえ、今日帰り寄り道しよ？',
    '自分: いいよ、いつもの駅で待ってる',
    '相手: なんか今日、忘れたくない日になりそう',
  ],
  sns: '夏の終わりって、なんで少しだけ静かなんだろう。 #架空自分史',
  search: ['好きな人 脈あり サイン', '夏祭り 帰り道 告白', '写真 現像 安い'],
  diary: '今日は楽しかった。でも、楽しいだけじゃなかった。帰り道、少しだけ言葉が足りなかった気がする。',
  item: '制服のポケットに入れたままの、少し折れた映画の半券。',
  bgm: '夕立のあと、駅前ロータリー',
  characters: [
    {
      id: 'yui',
      name: 'ゆい',
      relationship: '同級生',
      age: '17',
      personality: '明るいけれど、ふとした瞬間に寂しさが出る。相手の変化に敏感。',
      speakingStyle: '短めで自然。少しだけ絵文字を使う。距離感は近いが、踏み込みすぎない。',
      backstory: '海の近くの町で育った。主人公とは放課後によく一緒に帰る仲。夏祭りの日から少しだけ空気が変わった。',
      avatar: 'ゆ',
      latestMessage: '今日、帰り寄り道しよ？',
      unread: 2,
    },
    {
      id: 'ren',
      name: '蓮',
      relationship: '幼なじみ',
      age: '17',
      personality: 'ぶっきらぼうだが面倒見がいい。昔から主人公を知っている。',
      speakingStyle: '少し雑で短い。照れ隠しが多い。たまに核心をつく。',
      backstory: '小学校からの幼なじみ。部活帰りに駅前でよく会う。言葉数は少ないが、主人公のことをよく見ている。',
      avatar: '蓮',
      latestMessage: 'お前、今日なんか変だったぞ',
      unread: 0,
    },
    {
      id: 'mika',
      name: '美佳',
      relationship: '部活の先輩',
      age: '18',
      personality: '落ち着いていて優しい。少し大人っぽく、相談相手になってくれる。',
      speakingStyle: '丁寧だけど親しみがある。語尾はやわらかい。',
      backstory: '部活の先輩。卒業を控えていて、町を離れる予定。主人公に何かを残そうとしている。',
      avatar: '美',
      latestMessage: 'あと少しで夏も終わるね',
      unread: 1,
    },
  ],
  albums: [
    {
      id: 'summer',
      title: '夏の終わり',
      description: '放課後、夏祭り、駅前。少しだけ言葉が足りなかった季節。',
      coverUrl: '/feature-album.jpg',
      photos: [
        {
          id: 'summer-1',
          title: '放課後の教室',
          caption: '誰もいない教室に、夕方の光だけが残っていた。',
          date: '1999.07.12 16:42',
          imageUrl: '/feature-diary.jpg',
        },
        {
          id: 'summer-2',
          title: '夏祭りの帰り道',
          caption: '屋台の明かりが遠くなっても、まだ帰りたくなかった。',
          date: '1999.08.15 21:18',
          imageUrl: '/feature-sns.jpg',
        },
        {
          id: 'summer-3',
          title: '駅前のコンビニ',
          caption: 'アイスを買っただけなのに、妙に覚えている夜。',
          date: '1999.08.23 20:07',
          imageUrl: '/feature-search.jpg',
        },
      ],
    },
    {
      id: 'room',
      title: '自分の部屋',
      description: 'ポスター、古い机、散らかったプリント。誰にも見せなかった日々。',
      coverUrl: '/feature-item.jpg',
      photos: [
        {
          id: 'room-1',
          title: '机の上',
          caption: '使いかけのペンと、書けなかった手紙。',
          date: '1999.09.02 23:14',
          imageUrl: '/feature-item.jpg',
        },
        {
          id: 'room-2',
          title: '夜の部屋',
          caption: '窓の外から、遠くの電車の音が聞こえた。',
          date: '1999.09.10 00:31',
          imageUrl: '/feature-music.jpg',
        },
      ],
    },
  ],
};
